version: "3.0"

services:
  nginx:
    build: .docker/nginx
    container_name: nginx
    restart: always
    tty: true
    stdin_open: true
    ports:
      - 8000:80
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - app

  redis:
    image: redis:6.0
    expose:
      - 6379
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: app
    entrypoint: dockerize -template ./.docker/app/.env:.env -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
    environment:
      - DB_HOST=db
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root
    networks:
      - app-network
    depends_on:
      - db
      - redis

  db:
    build: .docker/mysql
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports:
      - 3306
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
