version: "3"

services:
  nginx:
    build: .docker/nginx
    container_name: nginx
    restart: always
    tty: true
    stdin_open: true
    ports:
      - 8000:80
    volumes:
      - .:/var/www
    networks:
      - app-network

  redis:
    image: redis:6.0
    expose:
      - 6379
    networks:
      - app-network

  app:
    build: .
    container_name: app
    volumes:
      - .:/var/www
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
